# Generated by Django 4.2.6 on 2023-10-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("startDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("certificate", models.BooleanField(default=False)),
            ],
        ),
    ]
